name: update-api

on:
  schedule:
    - cron: "0 6 1 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    defaults:
      run:
        working-directory: ban-api

    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: api

      - name: install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          ignore-nothing-to-cache: true
          version: "latest"

      - name: update dependencies
        run: uv sync --all-groups --upgrade

      - name: create pr
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): `uv sync --all-groups --upgrade`"
          title: "chore(deps): update `uv` dependencies"
          body: "`uv` detected new versions for some dependencies."
          base: "api"
          branch: "chore/deps"
          delete-branch: true
